# This is a basic workflow to help you get started with Actions

name: "Publish CDN "


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cdn:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # - name: Install Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      # - name: Upgrade pip
      #   run: |
      #     python3 -m pip install --upgrade pip
      # - name: Get pip cache dir
      #   id: pip-cache
      #   run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      # - name: Cache dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ steps.pip-cache.outputs.dir }}
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      # - name: Install dependencies
      #   run: python3 -m pip install -r ./requirements_dev.txt
      # - name: Build Docs
      #   run: |
      #     sphinx-build -M html docsrc ./docsrc/_build/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cdn
          destination_dir: cdn
